version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse-service
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - TZ=UTC
    volumes:
      - ./config.docker.json:/app/config.json
    networks:
      - warehouse-service-network
    command: sh -c "./scripts/run-migrations.sh && ./warehouse-service"

  mysql:
    image: mysql:8.0
    container_name: warehouse-service-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: warehouse_service
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - warehouse-service-network

networks:
  warehouse-service-network:
    driver: bridge

volumes:
  mysql_data: