CREATE TABLE warehouses (
    id        INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name      VARCHAR(255) NOT NULL,
    location  VARCHAR(255) NOT NULL,
    address   VARCHAR(500) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE = InnoDB;